### ISSUE TITLE
loading pretrain model

### ISSUE THREAD

**Issue by HOSSEINFEIZ** [nilmtk/nilmtk-contrib#13]
how is it possible to use the API for loading a pre-train model?

**Comment by Rithwikksvr** [comment]
Currently not all the models support pre-trained models. Mean algorithm is one of them that supports pre trained model. 


Specify this in the algorithm 'pretrained-model-path:'folder_name'.'  This is for loading a pre-trained model.

Specify this in the algorithm 'save-model-path':'folder_name' to save a model. This is  for saving thr model.

**Comment by Rithwikksvr** [comment]
We are looking for contributors to contribute the part for saving and loading algorithms.
