### ISSUE TITLE
no output graph. 

### ISSUE THREAD

**Issue by Hessen525** [nilmtk/nilmtk-contrib#15]
Hi Sir,
my output as following without any graph like your api_example.  
![output](https://user-images.githubusercontent.com/25447481/70535098-68c56500-1b97-11ea-9232-101a241f84ac.png)

![output2](https://user-images.githubusercontent.com/25447481/70535265-b2ae4b00-1b97-11ea-847c-f2c89b753b4d.png)

Could you give me a idea how to fix it? Thanks!

**Comment by Rithwikksvr** [comment]
Hello,

Can you please tell us clearly what the issue was?

**Comment by Hessen525** [comment]
> Hello,
> 
> Can you please tell us clearly what the issue was?

embarrased， I did not change False to True for plotting the graph!

**Comment by BillyLiii** [comment]
> > Hello,
> > Can you please tell us clearly what the issue was?
> 
> embarrased， I did not change False to True for plotting the graph!

Hi, where did you change this parameter?
