### ISSUE TITLE
Bug found when predict if train more than one application

### ISSUE THREAD

**Issue by Hessen525** [nilmtk/nilmtk-contrib#17]
Hi, 
![CT6D277`}UXAIO6 6OAOSJF](https://user-images.githubusercontent.com/25447481/70905564-2b515380-203f-11ea-9cfd-6210c30ecfec.png)

![)T74%HKZ ~KNAQR1{1KSMJJ](https://user-images.githubusercontent.com/25447481/70905746-9d299d00-203f-11ea-96de-f3e03f253508.png)

It always occurs error if train more than one application

**Comment by Rithwikksvr** [comment]
Resolved the issue @Hessen525 

Let us know if it still doesn't work!
