### ISSUE TITLE
add setup.py

### ISSUE THREAD

**Issue by alexander-belikov** [nilmtk/nilmtk-contrib#18]
why `cloning the repository in the Lib/Site-packages in your environment`
why not just add setup.py?

**Comment by levaphenyl** [comment]
It seems to be done in the `conda` branch.
@PMeira, what prevents your branch from being merged?

**Comment by PMeira** [comment]
@levaphenyl People probably forgot. I personally wasn't really involved much in the contrib repo, so I didn't check it much. 

I'll try to rebase it and merge it in a few days.

**Comment by PMeira** [comment]
I updated and merged the branch, as well as uploaded a new conda package. Prefer using that if you're not developing nilmtk-contrib itself.
