### ISSUE TITLE
experiment result

### ISSUE THREAD

**Issue by Hessen525** [nilmtk/nilmtk-contrib#19]
Hi, 
Thanks for your awesome work!  I have some question about the experiments as following:
1. How to get a similar result as you post 
![C 2VZM 2KZ88@7K@GDC5SI0](https://user-images.githubusercontent.com/25447481/71766225-8ab4cc00-2f38-11ea-9610-47350b40c97c.png)
I run your code and set the same dataset and epochs for every algorithm, but the result is different from yours. 

2. Do you think this is a good result ？
 
 `'appliances': ['washing machine'],
'methods': {

     'WindowGRU': WindowGRU({'n_epochs':30}),
     'RNN': RNN({'n_epochs':50}),
     'DAE': DAE({'n_epochs':50}),
     'Seq2Point': Seq2Point({'n_epochs':50}),
     'Seq2Seq': Seq2Seq({'n_epochs':50}),
     'Convlstm': Convlstm({'n_epochs':30,}),
},
'train': {
    'datasets': {
        '1': {
            'path': 'C:/Users/Jia/Desktop/NILM/ukdale.h5',
            'buildings': {
                1: {
                    'start_time': '2014-01-05',
                    'end_time': '2014-02-05'
                },
            }

        }
    }
},
'test': {
    'datasets': {
        'Datport': {
            'path': 'C:/Users/Jia/Desktop/NILM/ukdale.h5',
            'buildings': {
                1: {
                    'start_time': '2014-04-1',
                    'end_time': '2014-04-7'
                },
            }
        }
    },
    'metrics': ['mae','rmse' ]
}
`

![ZFSV82WUDAU693~H7$GL6BY](https://user-images.githubusercontent.com/25447481/71766315-a2408480-2f39-11ea-8f39-4e515140aacc.png)
![3RAJ63S9CICJ92JH6RFT~$3](https://user-images.githubusercontent.com/25447481/71766319-aff60a00-2f39-11ea-81c9-ee565cc03098.png)

Thanks！

**Comment by Geckao** [comment]
I would like to point out that I have the exact same problem as you, regarding your first question. In fact, I wasn't able to reproduce any result of the article.
I believe there is a bug somewhere in the API, I therefore have no clue where to look.

**Comment by Rithwikksvr** [comment]
Hello @Geckao @Hessen525 

I was busy during the past few days, so I couldn't get back to you. Recently, I made a change in the API, that was the reason for this issue. Give me sometime, I'll get the issues resolved soon!

**Comment by Geckao** [comment]
Hello @Rithwikksvr 

Thank you for your quick reply. Do you know if there is a version I can revert to in order to remove this issue ? If so, which one ?

Thank you !

**Comment by Rithwikksvr** [comment]
Hey @Geckao @Hessen525 

Once download the latest version of the repository and try using it. 

Also, you have been doing the experiment wrong.

The notebook for the experiment mentioned is [this](https://github.com/nilmtk/buildsys2019-paper-notebooks/blob/master/Cross%20Dataset%20Neurals%2C%20CO%2C%20Hart%2C%20FHMM.ipynb)

The table mentioned is from this notebook!

**Comment by Hessen525** [comment]
@Rithwikksvr Hi, 
I download the newest version of the repository and ukdale database and used the exact same parameters as mentioned in your notebook, but still can not reproduce any result of this article.

**Comment by Hessen525** [comment]
@Geckao hi, Could you reproduce the result as the article mentioned right now?

**Comment by Rithwikksvr** [comment]
@Hessen525 Can you also use the latest copy of api.py in NILMTK? The latest api.py has not been added to an installer, so can you manually just copy the api.py?

Also, just run the notebook specified above. Dont just use the same parameters, use the same training and testing data as well.

**Comment by Hessen525** [comment]
Hi, @Rithwikksvr:
Thanks so much for your help, I try to reproduce the experiment by another two computers, but I got same new errors. the steps as following:
1. install nilmtk(as mentioned in nilmtk repo):
      conda create --name nilmtk-env  
      conda config --add channels conda-forge
      conda activate nilmtk-env
      conda install -c nilmtk nilmtk
2. download nilmtk-contrib from your repo and then decompress them to the Lib/site-packages and change the name as nilmtk_contrib. 

so, the relationship as following:  Lib/site-packages/nilmtk, Lib/site-packages/nilmtk_contrib, Lib/site-packages/main.ipynb

main.ipynb:

<img width="716" alt="1" src="https://user-images.githubusercontent.com/25447481/72785875-28add380-3c67-11ea-8716-c2de67532792.png">
<img width="624" alt="2" src="https://user-images.githubusercontent.com/25447481/72785894-33686880-3c67-11ea-9b3c-f339dd0c7f56.png">
<img width="702" alt="3" src="https://user-images.githubusercontent.com/25447481/72785932-48dd9280-3c67-11ea-8f54-f12b3be40614.png">

Is the step correct?
