### ISSUE TITLE
how many metrics can we use now?

### ISSUE THREAD

**Issue by Wusir2018** [nilmtk/nilmtk-contrib#21]
Hello everyone,
Thanks for your contribution! But I have a question about the metrics.
How many metrics can we use now? I just find `mae` and `rmse`, I didn't find `F1 score` and `accuracy` and others.
Thank you very much!

**Comment by klemenjak** [comment]
Hi,

you'll find the metrics here: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/losses.py

best,
C

**Comment by Wusir2018** [comment]
Hi @klemenjak   
Thank you very much! It works!
If I want to use any other metrics like `accuracy`? I just only add function `accuracy` in `losses.py` like this?
![accuracy](https://user-images.githubusercontent.com/51500032/72489329-aed4af00-384e-11ea-8246-386df7dfa37c.png)

**Comment by klemenjak** [comment]
I think that could work though I would test it extensively to be sure.

Why do you want to use the accuracy score when F1 is available?

**Comment by Wusir2018** [comment]
Hi @klemenjak,
Thank you very much! I have alredy test it and it works! 
HHHHHH, I just want to compared with many metrics. `F1 score` is good metric. But I think `accuracy` is common metric, and maybe should be considered, too. 
Thank you very much!

**Comment by klemenjak** [comment]
You are welcome

**Comment by Wusir2018** [comment]
@klemenjak  :) 
Best Wishes!

**Comment by Wusir2018** [comment]
Hi, @klemenjak 
I am so sorry to trouble you again.
I have questions in this code:
![1111](https://user-images.githubusercontent.com/51500032/72527430-b5414600-38a3-11ea-9065-3fc4a3b5f5df.png)
1. if we set appliances as `['fridge','light', 'microwave']`, in `house 1`, we have `three light`, but I test the code, the light is `light_1`, so how can we chose other light?
2. if we set `'power': {'mains': ['apparent','active'],'appliance': ['apparent','active']}`, appliances as `['fridge','light', 'microwave']`, in `house 1`, we have `two mains`, but when we do disaggregate, the `totalpower` is `mains_1`, why?  Why the totalpower is not the `sum` of `['fridge','light', 'microwave']` ?
Could you help me? Thank you very much!

**Comment by Rithwikksvr** [comment]
Hey @Wusir2018 

1. Currently at the moment, we haven't added the functionality to choose a specific light/appliance.
2. The sum of appliances is not equal to mains, since the total power consists of many other appliances in the household. If you want to have the `totalpower `equal to the sum of appliances, you can use `'artificial_aggregate':True`.

**Comment by Wusir2018** [comment]
Hello @klemenjak,
Thanks for your reply.
Your reply is too clear, which helps me a lot.
Thank you very much!  :)

**Comment by klemenjak** [comment]
I wasn’t the author of the latest reply ;)

**Comment by Wusir2018** [comment]
@klemenjak 
I am so sorry that I make  this mistake！

**Comment by Wusir2018** [comment]
@Rithwikksvr 
I am Sorry, I didn't reply to you in the first time. I made a mistake. Please forgive me. Thank you very much for your reply. It's very useful. 
Best Wishes!

**Comment by Rithwikksvr** [comment]
Hello @Wusir2018 no need to apologize. I should have responded in time, but I was busy.

Thanks to @klemenjak for responding!!

**Comment by klemenjak** [comment]
You are welcome. I don’t think you need to apologize!

**Comment by Wusir2018** [comment]
Hey @klemenjak , @Rithwikksvr
Thank you very much! You help me a lot!
I hope to join you in the near future.
Best wishes!  :)
