### ISSUE TITLE
I can't use AFHMM and AFHMM_SAC

### ISSUE THREAD

**Issue by Wusir2018** [nilmtk/nilmtk-contrib#22]
Hello everyone,
Thanks for your contribution!
I can use the `DAE, Seq2Point, Seq2Seq, RNN, WindowGPU`, but when I change them to `AFHMM and AFHMM_SAC`
![contribute](https://user-images.githubusercontent.com/51500032/72331776-b59adf00-36f3-11ea-9c99-13444848cddc.png)

get the error:

`Started training for  AFHMM
Joint training for  AFHMM
............... Loading Data for training ...................
Loading data for  Dataport  dataset
Loading building ...  1

Done loading data all meters for this chunk.
Dropping missing values
Train Jointly
(2318, 1) (2318, 1) MultiIndex([('power', 'apparent')],
           names=['physical_quantity', 'type']) MultiIndex([('power', 'active')],
           names=['physical_quantity', 'type'])
Finished Training
Finished training for  AFHMM
Started training for  AFHMM
Joint training for  AFHMM
............... Loading Data for training ...................
Loading data for  Dataport  dataset
Loading building ...  1

Done loading data all meters for this chunk.
Dropping missing values
Train Jointly
(2318, 1) (2318, 1) MultiIndex([('power', 'apparent')],
           names=['physical_quantity', 'type']) MultiIndex([('power', 'active')],
           names=['physical_quantity', 'type'])
Finished Training
Finished training for  AFHMM
Started training for  Mean
Joint training for  Mean
............... Loading Data for training ...................
Loading data for  Dataport  dataset
Loading building ...  1

Done loading data all meters for this chunk.
Dropping missing values
Train Jointly
(2318, 1) (2318, 1) MultiIndex([('power', 'apparent')],
           names=['physical_quantity', 'type']) MultiIndex([('power', 'active')],
           names=['physical_quantity', 'type'])
Finished training for  Mean
Joint Testing for all algorithms
Loading data for  Datport  dataset
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Dropping missing values
Generating predictions for : AFHMM
Traceback (most recent call last):

  File "<ipython-input-62-e79c405b4836>", line 54, in <module>
    api_res = API(redd)

  File "F:\Anaconda3\envs\nilmtk\lib\site-packages\nilmtk\api.py", line 59, in __init__
    self.experiment(params)

  File "F:\Anaconda3\envs\nilmtk\lib\site-packages\nilmtk\api.py", line 118, in experiment
    self.test_jointly(d)

  File "F:\Anaconda3\envs\nilmtk\lib\site-packages\nilmtk\api.py", line 292, in test_jointly
    self.call_predict(self.classifiers)

  File "F:\Anaconda3\envs\nilmtk\lib\site-packages\nilmtk\api.py", line 339, in call_predict
    gt_overall,pred_overall[name]=self.predict(clf,self.test_mains,self.test_submeters, self.sample_period,'Europe/London')

  File "F:\Anaconda3\envs\nilmtk\lib\site-packages\nilmtk\api.py", line 386, in predict
    pred_list = clf.disaggregate_chunk(test_elec)

  File "F:\Anaconda3\envs\nilmtk\lib\site-packages\nilmtk_contrib\disaggregate\afhmm.py", line 226, in disaggregate_chunk
    self.arr_of_results.append(d[i])

  File "<string>", line 2, in __getitem__

  File "F:\Anaconda3\envs\nilmtk\lib\multiprocessing\managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)

KeyError: 0`

Could you help me?

**Comment by Wusir2018** [comment]
I download the `nilmtk-contrib.zip` and decompress them to the `Lib/site-packages` and change the name as `nilmtk_contrib`. I didn't do any other thing, so my steps is right?

**Comment by Rithwikksvr** [comment]
The steps are correct. Can you please place the whole code you were using including the dataset and timestamps?

**Comment by Wusir2018** [comment]
Hi @Rithwikksvr ,
I am sorry that I don't know how to present the code clearly to you. I can only choose screenshots.
Thank you very much!
![111](https://user-images.githubusercontent.com/51500032/72489644-a03ac780-384f-11ea-9ef4-a4d6ac8d2509.png)
![111222](https://user-images.githubusercontent.com/51500032/72489649-a16bf480-384f-11ea-84fa-5fb15db7395e.png)

**Comment by Rithwikksvr** [comment]
I am working on it. Give me sometime!

**Comment by Wusir2018** [comment]
@Rithwikksvr  Thank you very much!

**Comment by Wusir2018** [comment]
hello @Rithwikksvr 
I am sorry to trouble you again.
Could you help me about this question?
I can't run the algorithm with AMPds data.
Thank you very much!
[https://github.com/nilmtk/nilmtk-contrib/issues/24](url)

**Comment by PMeira** [comment]
@Wusir2018 This is an old issue but since the behavior is present in other issues, I have to say: please, never post code as pictures. You're making it harder for everyone -- do you really expect anyone that tries to help you to retype the code from a picture?!

**Comment by Wusir2018** [comment]
@PMeira  Thank you for your advice, I'll bear it in mind. Thank you very much!
Best wishes!

**Comment by PMeira** [comment]
With the current version, couldn't find any issue. I recommend checking if the dataset is converted correctly and the Python environment is correct.

Here's the text version of the code with minor changes:

```python
from nilmtk.api import API
from nilmtk.disaggregate import Mean
from nilmtk_contrib.disaggregate import AFHMM, AFHMM_SAC

experiment1 = {
    'power': {
        'mains': ['apparent', 'active'],
        'appliance': ['apparent', 'active']
    }, 
    'sample_rate': 60,
    'appliances': ['fridge'],
    'methods': {
        'AFHMM': AFHMM({}),
        'AFHMM_SAC': AFHMM_SAC({}),
        'Mean': Mean({})
    },
    
    'train': {
        'datasets': {
            'REDD': {
                'path': '/data/redd.h5', 
                'buildings': { 
                    1: {
                        'start_time': '2011-04-20', 
                        'end_time': '2011-04-21'
                    }
                }
            }
        }
    },

    'test': {
        'datasets': {
            'REDD': {
                'path': '/data/redd.h5', 
                'buildings': { 
                    1: {
                        'start_time': '2011-04-21', 
                        'end_time': '2011-04-22'
                    }
                }
            },
        },
        'metrics':['rmse']
    }
}

api_results_experiment_1 = API(experiment1) 
errors_keys = api_results_experiment_1.errors_keys 
errors = api_results_experiment_1.errors

for i in range(len(errors)):
    print(errors_keys[i])
    print(errors[i])
    print("\n\n")
```

and the output for the API call:

```text
Joint Testing for all algorithms
Loading data for  REDD  dataset
Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Dropping missing values
Generating predictions for : AFHMM
Generating predictions for : AFHMM_SAC
Generating predictions for : Mean
............  rmse  ..............
             AFHMM  AFHMM_SAC       Mean
fridge  100.130862  78.923794  82.533957
```

**Comment by Wusir2018** [comment]
@PMeira Thank you very much!
