### ISSUE TITLE
about experiement

### ISSUE THREAD

**Issue by hk123456789Q** [nilmtk/nilmtk-contrib#23]
Thank you for your work. I encountered a problem while debugging the project, specifically in the "pandas" package. I don't know if it is a version problem. I hope to get your help. In addition, the data set "dataport.hdf5" and What is "dred.h5"? I didn't find the corresponding data set. If you have any information to share, I would really appreciate it.
![图片](https://user-images.githubusercontent.com/52767277/73659886-12296280-46d2-11ea-8e0b-e5809ff7901e.png)
File "G:\Anaconda\envs\ceshi\lib\site-packages\pandas\core\generic.py", line 5273, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

**Comment by Rithwikksvr** [comment]
Hello @hk123456789Q 

I think you might be using a different version of pandas. Tat might be causing the 'ix' error. As far as I now, it was downgraded after a particular version, restore back to the one for which it works. 

The '.h5' files are designed for handling by NILMTK. So, DRED already has a h5 file that is mentioned on its website. 

"dataport.h5" can be generated by using NILMTK scripts if you have the data.  First download the data and follow this [link](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb)

**Comment by Hessen525** [comment]
Hello @Rithwikksvr
Could you give some idea for fixing that problem as mentioned in: https://github.com/nilmtk/nilmtk-contrib/issues/19    
or more detail for how to make the api work, 

THANKS!

**Comment by hk123456789Q** [comment]
I have probably completed the use of the api, and can basically complete simple basic experiments. The nilmtk library that needs to be imported needs to be basically modified by the author, with little change. For other uses, you can refer to the notes written by the author. In addition, do you have the data set mentioned in the program, I downloaded it is not very convenient, I am happy to communicate with you. @Hessen525

**Comment by Hessen525** [comment]
@hk123456789Q
I just have REDD and UK-dale. Do you have a Wechat?
 I have no idea why it don't work for the newest version in my two computers(use same steps in which old version working) , both two encounter same error as post.

**Comment by hk123456789Q** [comment]
> 
> 
> Hello @hk123456789Q
> 
> I think you might be using a different version of pandas. That might be causing the 'ix' error. As far as I now, it was downgraded after a particular version, restore back to the one for which it works.
> 
> The '.h5' files are designed for handling by NILMTK. So, DRED already has a h5 file that is mentioned on its website.
> 
> "dataport.h5" can be generated by using NILMTK scripts if you have the data. First download the data and follow this [link](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb)

I tried to change a version of pandas, using 0.24.2, the program is no problem. Thank you.

**Comment by hk123456789Q** [comment]
> 
> 
> @hk123456789Q
> I just have REDD and UK-dale. Do you have a Wechat?
> I have no idea why it don't work for the newest version in my two computers(use same steps in which old version working) , both two encounter same error a
