### ISSUE TITLE
Cannot import FHMM_EXACT 

### ISSUE THREAD

**Issue by Shibumi497** [nilmtk/nilmtk-contrib#25]
Hi

I am following the tutorial api and I am facing this problem :
![problem nilmtk disaggregate 2](https://user-images.githubusercontent.com/60926736/76338423-f4ff3980-62f8-11ea-8bae-7078540d3663.png)

I can import the basics (that were already in the first nilmtk if I remember well) as CO, Mean, Hart85, but not FHMM_EXACT. The new ones from the nilmtk_contrib I can call them, but not using __init__.

![problem nilmtk path nilmtk_contrib 2](https://user-images.githubusercontent.com/60926736/76339831-eca7fe00-62fa-11ea-81df-73ba6b1ac9c1.png)

Thanks in advance for your help :)

**Comment by klemenjak** [comment]
FHMM Exact is found at:

```
from nilmtk.disaggregate import Mean, FHMMExact, CO, Hart85
```
