### ISSUE TITLE
Facing issue while reproducing the results of train/test across multiple buildings and datasets.

### ISSUE THREAD

**Issue by khurramch** [nilmtk/nilmtk-contrib#28]
hello,
I need your help to solve this specific issue.I am trying to run the [notebook](https://github.com/nilmtk/buildsys2019-paper-notebooks/blob/master/Cross%20Dataset%20FHMM's%20and%20DSC.ipynb) Here is the error shown while running the code.
![image](https://user-images.githubusercontent.com/34025513/81909121-9188d500-95e3-11ea-823d-7a956d5d8cb3.png)

**Comment by PMeira** [comment]
Looks like something related to the datasets, maybe missing data due an error. I'd suggest trying with just one dataset first.

It's not clear from the repo but you need to have previously downloaded and converted the datasets (converted them using NILMTK). If you've done that, it's possible the conversion of one of them failed somewhere.

**Comment by PMeira** [comment]
Closing, probably a stale ticket.
