### ISSUE TITLE
Link failure

### ISSUE THREAD

**Issue by M-h-2019** [nilmtk/nilmtk-contrib#30]
hello,
   I want to know the paper of the disaggregationmethod, but the paper link you gave in the readme document is invalid, I hope you can update it, thank you.

**Comment by PMeira** [comment]
Thanks, I'll update the link -- that would be a copy of https://doi.org/10.1145/3360322.3360844
There's also https://aiforgood2020.github.io/papers/AI4SG_paper_50.pdf
