### ISSUE TITLE
AFHMM+SAC: parameter chunk_wise_training is hardcoded

### ISSUE THREAD

**Issue by levaphenyl** [nilmtk/nilmtk-contrib#36]
In the `AFHMM_SAC` class [`__init__`](https://github.com/nilmtk/nilmtk-contrib/blob/master/nilmtk_contrib/disaggregate/afhmm_sac.py#L38) function, the parameter `chunk_wise_training` is hardcoded.
Consequence: the AFHMM+SAC will be trained jointly, no matter what the user specified. Handy, when the training data does not fit in RAM :).

This issue is just for referencing, I will open a PR.

**Comment by Rithwikksvr** [comment]
Yes, if we want to make it support multi chunk training, then we need to compute the average of A, B, Transition matrix over the different chunks

**Comment by Rithwikksvr** [comment]
Feel feel to submit a pull request. But, @nipunbatra or @MingjunZhong  can tell if computing the average values over different chunks is a good idea or not

**Comment by levaphenyl** [comment]
> if we want to make it support multi chunk training, then we need to compute the average of A, B, Transition matrix over the different chunks

Understood. I will adapt the PR with the changes.

**Comment by levaphenyl** [comment]
> Feel feel to submit a pull request. But, @nipunbatra or @MingjunZhong can tell if computing the average values over different chunks is a good idea or not

PR is [open](https://github.com/nilmtk/nilmtk-contrib/pull/37). Any review is appreciated.
