### ISSUE TITLE
changes to plot in api.py, not reflected

### ISSUE THREAD

**Issue by akritikts** [nilmtk/nilmtk-contrib#44]
for i in gt_overall.columns:

                plt.figure()            
                #plt.plot(self.test_mains[0],label='Mains reading')
                plt.plot(gt_overall[i],label='Ground Truth')
                for clf in pred_overall:                
                    plt.plot(pred_overall[clf][i],label=clf)
                    plt.xticks(rotation=90)
                plt.title(i)
                plt.legend()
            plt.show()

The labels on the x-axis are not rotated.
![image](https://user-images.githubusercontent.com/15141275/94427610-b8325b80-01d2-11eb-9085-722ae699d766.png)

**Comment by PMeira** [comment]
I don't see how that's a NILMTK-contrib or even NILMTK issue.
