### ISSUE TITLE
Train Test Split in RNN

### ISSUE THREAD

**Issue by JoseDosSantos** [nilmtk/nilmtk-contrib#46]
Hi!
Since the latest update which switched from sklearn train_test_split to the built in keras method the RNN implementation doesnt work anymore, presumably because the fit function still takes train_x and train_y as inputs, which should be train_main and power respectively instead. Should be easy to fix :)

```
model.fit(
    train_x, train_y,
    validation_split=.15,
    epochs=self.n_epochs,
    batch_size=self.batch_size,
    callbacks=[ checkpoint ],
    )
```

Cheers!

**Comment by PMeira** [comment]
Yep, thanks @JoseDosSantos! Indeed a simple fix.
