### ISSUE TITLE
You're calling a NumPy function on a CVXPY expression.

### ISSUE THREAD

**Issue by habring** [nilmtk/nilmtk-contrib#70]
When I try to apply the trained method afhmm to new data I get the following error:

> Traceback (most recent call last):
>   File "/home/habring/anaconda3/envs/nilm-contrib/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/home/habring/anaconda3/envs/nilm-contrib/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/habring/anaconda3/envs/nilm-contrib/lib/python3.7/site-packages/nilmtk_contrib/disaggregate/afhmm.py", line 157, in disaggregate_thread
>     total_observed_reading+=cvx_state_vectors[appliance_id]@means_vector[appliance_id]
>   File "/home/habring/anaconda3/envs/nilm-contrib/lib/python3.7/site-packages/cvxpy/expressions/expression.py", line 721, in __array_ufunc__
>     raise RuntimeError(__NUMPY_UFUNC_ERROR__)
> RuntimeError: 
> You're calling a NumPy function on a CVXPY expression. This is prone to causing
> errors or code that doesn't behave as expected. Consider using one of the
> functions documented here: https://www.cvxpy.org/tutorial/functions/index.html

I think I have narrowed down the issue already. Apparently in line 157 in nilmtk_contrib/disaggregate/afhmm.py you do something like
`numpy array += cvxp variable @ numpy array`

I think since the left-hand side of the += is a numpy array, the operator @ is interpreted as a numpy function and then the error is raised.
Suggestions are welcome.

Best,
Andi

**Comment by habring** [comment]
I could resolve this by donwgrading cvxpy to version 1.0.

**Comment by Rebecca29** [comment]
> I could resolve this by donwgrading cvxpy to version 1.0.

Hi, I encountered exactly the same issue, I tried downgrading by 
pip install -I cvxpy==1.0.xx 
or pip install cvxpy==1.0.xx, 
I tried a lot of 1.0 versions, all the installations are failed. Could you tell which version you installed?

**Comment by habring** [comment]
Hi,

I'm not 100% sure anymore. But maybe try the following. 

1. Create a fresh conda environment.
2. Use conda to install scikit-learn=0.21, keras=2.2.4, and cvxpy=1.0.0.
3. Afterwards install nilmtk-contrib via `conda install -c conda-forge -c nilmtk nilmtk-contrib`

Also, generally when I am forced to work with conda, like in this case, since nilmtk uses conda as an environment manager, I try to stick to conda for installing packages if it is not necessary to invoke pip. I don't know if this makes a difference but you could try.

Best,
Andi

**Comment by Rebecca29** [comment]
Thank you for your env info, the DSC finally can run now, but the AFHMM and AFHMM+SAC cannot work anymore... Maybe because of the downgrading of Keras? I'm on the verge of breaking down now...
