### ISSUE TITLE
No module named 'nilmtk.disaggregate

### ISSUE THREAD

**Issue by HouKun-github** [nilmtk/nilmtk-contrib#9]
How does nilmtk-contrib work with nilmk, what is the specific operation under Anacoda, thank you, I have the same problem as the previous scholar, "No module named 'nilmtk.disaggregate'"

**Comment by Rithwikksvr** [comment]
Hellow @hk123456789Q  Sorry for not getting back to you sooner. Currently the repository  is in development phase. In the meanwhile, you can copy the api.py, losses.py and the algorithms to the disaggregate folder. 

Then you can do the respective imports. Feel free to get back to us in case of any issues!

**Comment by hk123456789Q** [comment]
Hi，thank you for your help,I have solved the above problem, but there is a new problem. It is about the neural-disaggregator. I can't configure the corresponding development environment. Do you have any suggestions?

**Comment by hk123456789Q** [comment]
> 
> 
> Hellow @hk123456789Q Sorry for not getting back to you sooner. Currently the repository is in development phase. In the meanwhile, you can copy the api.py, losses.py and the algorithms to the disaggregate folder.
> 
> Then you can do the respective imports. Feel free to get back to us in case of any issues!

Hi，thank you for your help,I have solved the above problem, but there is a new problem. It is about the neural-disaggregator. I can't configure the corresponding development environment. Do you have any suggestions?just like this  “Using TensorFlow backend.”

**Comment by Rithwikksvr** [comment]
Hello @hk123456789Q, to use the neural-disaggregation algorithms you can install keras with tensorflow backend. We are currently in the process of developing an conda installer for nilmtk-contrib. Will update you once it is done.  

First, create a new environment. Then install nilmtk using conda(How to install is there in nilmtk documentation). Then, you install keras in the same environment and then start using the API.

**Comment by hk123456789Q** [comment]
> 
> 
> Hello @hk123456789Q, to use the neural-disaggregation algorithms you can install keras with tensorflow backend. We are currently in the process of developing an conda installer for nilmtk-contrib. Will update you once it is done.
> 
> First, create a new environment. Then install nilmtk using conda(How to install is there in nilmtk documentation). Then, you install keras in the same environment and then start using the API.
> 
> Get back to me if there are any issues. We can have a skype call if needed for the same. You can share your skype id at the email address specified at my homepage.

Thank you for your reply, I am trying to configure the development environment, if there is any problem, I will get in touch with you. Thanks again

**Comment by Wusir2018** [comment]
Hello @hk123456789Q  @Rithwikksvr ,
I can use the `DAE, Seq2Point, Seq2Seq, RNN, WindowGPU`,  but  I can't use `AFHMM and AFHMM_SAC`. 
I download the `nilmtk-contrib.zip` and decompress them to the `Lib/site-packages` and change the name as `nilmtk_contrib`. I didn't do any other thing, so are my steps right?
the error detail [https://github.com/nilmtk/nilmtk-contrib/issues/22](url)
Could you help me?

**Comment by PMeira** [comment]
For future reference, nowadays prefer the conda package.
